# Spam Classifier

In [44]:
#Importing necessary packages for the classification 
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.svm import SVC  
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [24]:
#Importing data into a dataframe
spam=pd.read_csv("spambase.data.csv",header=None)
spam_data=spam.drop(57, axis=1)
print(spam_data)
spam_label=spam[57]

        0     1     2    3     4     5     6     7     8     9   ...    47  \
0     0.00  0.64  0.64  0.0  0.32  0.00  0.00  0.00  0.00  0.00  ...   0.0   
1     0.21  0.28  0.50  0.0  0.14  0.28  0.21  0.07  0.00  0.94  ...   0.0   
2     0.06  0.00  0.71  0.0  1.23  0.19  0.19  0.12  0.64  0.25  ...   0.0   
3     0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...   0.0   
4     0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...   0.0   
5     0.00  0.00  0.00  0.0  1.85  0.00  0.00  1.85  0.00  0.00  ...   0.0   
6     0.00  0.00  0.00  0.0  1.92  0.00  0.00  0.00  0.00  0.64  ...   0.0   
7     0.00  0.00  0.00  0.0  1.88  0.00  0.00  1.88  0.00  0.00  ...   0.0   
8     0.15  0.00  0.46  0.0  0.61  0.00  0.30  0.00  0.92  0.76  ...   0.0   
9     0.06  0.12  0.77  0.0  0.19  0.32  0.38  0.00  0.06  0.00  ...   0.0   
10    0.00  0.00  0.00  0.0  0.00  0.00  0.96  0.00  0.00  1.92  ...   0.0   
11    0.00  0.00  0.25  0.0  0.38  0.25  0.25  0.00  0.00  0.00 

# Guassian Naive Bayes

In [70]:
#splitting data into train and testing data using kfolds
spam_data=np.array(spam_data)
kfold=KFold(n_splits=3, shuffle=True)
for train_index, test_index in kfold.split(spam_data):
    print("TRAIN:", train_index, "TEST:", test_index)
    training_features,testing_features=spam_data[train_index], spam_data[test_index]
    training_labels,testing_labels=spam_label[train_index], spam_label[test_index]
    #training the training features with the training labels by fitting it into the Multinomial Naive Bayes Algorithm
    gnb = GaussianNB()
    gnb.fit(training_features,training_labels)
    labels_gnb=gnb.predict(testing_features)
    #Metric for Gaussian Naive Bayes Model: Accuracy.
    print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(testing_labels, labels_gnb)*100)
    #confusion Matrix: Guassian Naive Bayes
    conf_matrix=[[]]
    conf_matrix=confusion_matrix(testing_labels, labels_gnb)
    print("False Positive: ",conf_matrix[0][1])
    print("False Negative: ",conf_matrix[1][0])
    print("Confusion Matrix: ")
    print(confusion_matrix(testing_labels, labels_gnb))
    error_rate=100-metrics.accuracy_score(testing_labels, labels_gnb)*100
    print("Error rate for Gaussian Naive Bayes model (in %):", error_rate);
    print("----------------------------------------------------------------")

TRAIN: [   0    1    3 ... 4597 4598 4599] TEST: [   2    4    6 ... 4590 4596 4600]
Gaussian Naive Bayes model accuracy(in %): 81.35593220338984
False Positive:  250
False Negative:  36
Confusion Matrix: 
[[696 250]
 [ 36 552]]
Error rate for Gaussian Naive Bayes model (in %): 18.64406779661016
----------------------------------------------------------------
TRAIN: [   0    1    2 ... 4598 4599 4600] TEST: [   5    7    8 ... 4592 4595 4597]
Gaussian Naive Bayes model accuracy(in %): 81.7470664928292
False Positive:  260
False Negative:  20
Confusion Matrix: 
[[644 260]
 [ 20 610]]
Error rate for Gaussian Naive Bayes model (in %): 18.252933507170795
----------------------------------------------------------------
TRAIN: [   2    4    5 ... 4596 4597 4600] TEST: [   0    1    3 ... 4594 4598 4599]
Gaussian Naive Bayes model accuracy(in %): 82.84409654272667
False Positive:  233
False Negative:  30
Confusion Matrix: 
[[705 233]
 [ 30 565]]
Error rate for Gaussian Naive Bayes model (in %

# Multinomial Naive Bayes

In [71]:
kfold=KFold(n_splits=3, shuffle=True)
for train_index, test_index in kfold.split(spam_data):
    print("TRAIN:", train_index, "TEST:", test_index)
    training_features,testing_features=spam_data[train_index], spam_data[test_index]
    training_labels,testing_labels=spam_label[train_index], spam_label[test_index]
    #training the training features with the training labels by fitting it into the Multinomial Naive Bayes Algorithm
    clf = MultinomialNB()
    clf.fit(training_features,training_labels)
    #Metric for Multinomial Naive Bayes Model: Accuracy.
    labels_mnb=clf.predict(testing_features)
    print("Multinomial Naive Bayes model accuracy(in %):", metrics.accuracy_score(testing_labels, labels_mnb)*100)
    #confusion Matrix: Multinomial Naive Bayes
    conf_matrix=confusion_matrix(testing_labels, labels_mnb)
    print("False Positive: ",conf_matrix[0][1])
    print("False Negative: ",conf_matrix[1][0])
    print("Confusion Matrix: ")
    print(confusion_matrix(testing_labels, labels_mnb))  
    error_rate=100-metrics.accuracy_score(testing_labels, labels_mnb)*100
    print("Error rate for Multinomial Naive Bayes model (in %):", error_rate);
    print("----------------------------------------------------------------")

TRAIN: [   0    1    2 ... 4598 4599 4600] TEST: [   3    7    8 ... 4594 4596 4597]
Multinomial Naive Bayes model accuracy(in %): 78.42242503259452
False Positive:  147
False Negative:  184
Confusion Matrix: 
[[780 147]
 [184 423]]
Error rate for Multinomial Naive Bayes model (in %): 21.577574967405482
----------------------------------------------------------------
TRAIN: [   0    1    2 ... 4596 4597 4599] TEST: [   5   10   11 ... 4593 4598 4600]
Multinomial Naive Bayes model accuracy(in %): 81.35593220338984
False Positive:  145
False Negative:  141
Confusion Matrix: 
[[788 145]
 [141 460]]
Error rate for Multinomial Naive Bayes model (in %): 18.64406779661016
----------------------------------------------------------------
TRAIN: [   3    5    7 ... 4597 4598 4600] TEST: [   0    1    2 ... 4591 4595 4599]
Multinomial Naive Bayes model accuracy(in %): 78.01696020874103
False Positive:  160
False Negative:  177
Confusion Matrix: 
[[768 160]
 [177 428]]
Error rate for Multinomial N

# Bernoulli Naive Bayes

In [67]:
kfold=KFold(n_splits=3, shuffle=True)
for train_index, test_index in kfold.split(spam_data):
    print("TRAIN:", train_index, "TEST:", test_index)
    training_features,testing_features=spam_data[train_index], spam_data[test_index]
    training_labels,testing_labels=spam_label[train_index], spam_label[test_index]
    #training the training features with the training labels by fitting it into the Bernoulli Naive Bayes Algorithm
    bnb = BernoulliNB()
    bnb.fit(training_features,training_labels)
    labels_bnb=bnb.predict(testing_features)
    print("Bernoulli Naive Bayes model accuracy(in %):", metrics.accuracy_score(testing_labels, labels_bnb)*100)
    #confusion Matrix: Bernoulli Naive Bayes
    conf_matrix=confusion_matrix(testing_labels, labels_bnb)
    print("False Positive: ",conf_matrix[0][1])
    print("False Negative: ",conf_matrix[1][0])
    print("Confusion Matrix: ")
    print(confusion_matrix(testing_labels, labels_bnb))  
    error_rate=100-metrics.accuracy_score(testing_labels, labels_bnb)*100
    print("Error rate for Bernoulli Naive Bayes model (in %):", error_rate)
    print("----------------------------------------------------------------")

TRAIN: [   0    1    2 ... 4597 4599 4600] TEST: [   6   12   16 ... 4593 4595 4598]
Bernoulli Naive Bayes model accuracy(in %): 88.33116036505866
False Positive:  68
False Negative:  111
Confusion Matrix: 
[[861  68]
 [111 494]]
Error rate for Bernoulli Naive Bayes model (in %): 11.668839634941335
----------------------------------------------------------------
TRAIN: [   1    2    3 ... 4598 4599 4600] TEST: [   0    4    5 ... 4587 4596 4597]
Bernoulli Naive Bayes model accuracy(in %): 89.17861799217731
False Positive:  53
False Negative:  113
Confusion Matrix: 
[[871  53]
 [113 497]]
Error rate for Bernoulli Naive Bayes model (in %): 10.821382007822692
----------------------------------------------------------------
TRAIN: [   0    4    5 ... 4596 4597 4598] TEST: [   1    2    3 ... 4594 4599 4600]
Bernoulli Naive Bayes model accuracy(in %): 88.51924331376387
False Positive:  68
False Negative:  108
Confusion Matrix: 
[[867  68]
 [108 490]]
Error rate for Bernoulli Naive Bayes mod

# Decision Tree

In [68]:
kfold=KFold(n_splits=3, shuffle=True)
for train_index, test_index in kfold.split(spam_data):
    print("TRAIN:", train_index, "TEST:", test_index)
    training_features,testing_features=spam_data[train_index], spam_data[test_index]
    training_labels,testing_labels=spam_label[train_index], spam_label[test_index]
    #training the training features with the training labels by fitting it into the Decision tree Algorithm
    decisiontree = DecisionTreeClassifier(criterion = "gini", random_state = 100,max_depth=3, min_samples_leaf=5)
    decisiontree.fit(training_features,training_labels)
    #Metric for Decision Tree: Accuracy
    labels_decisiontree=decisiontree.predict(testing_features)
    print("Decision tree model accuracy(in %):", metrics.accuracy_score(testing_labels, labels_decisiontree)*100)
    #confusion Matrix: Decision Tree
    conf_matrix=confusion_matrix(testing_labels, labels_decisiontree)
    print("False Positive: ",conf_matrix[0][1])
    print("False Negative: ",conf_matrix[1][0])
    print("Confusion Matrix: ")
    print(confusion_matrix(testing_labels, labels_decisiontree)) 
    error_rate=100-metrics.accuracy_score(testing_labels, labels_decisiontree)*100
    print("Error rate for Decision Tree model (in %):", error_rate)
    print("----------------------------------------------------------------")

TRAIN: [   1    3    4 ... 4594 4595 4597] TEST: [   0    2    7 ... 4598 4599 4600]
Decision tree model accuracy(in %): 87.8096479791395
False Positive:  73
False Negative:  114
Confusion Matrix: 
[[843  73]
 [114 504]]
Error rate for Decision Tree model (in %): 12.190352020860502
----------------------------------------------------------------
TRAIN: [   0    1    2 ... 4598 4599 4600] TEST: [   6    8   11 ... 4594 4595 4597]
Decision tree model accuracy(in %): 88.20078226857888
False Positive:  63
False Negative:  118
Confusion Matrix: 
[[874  63]
 [118 479]]
Error rate for Decision Tree model (in %): 11.799217731421123
----------------------------------------------------------------
TRAIN: [   0    2    6 ... 4598 4599 4600] TEST: [   1    3    4 ... 4590 4591 4592]
Decision tree model accuracy(in %): 89.69341161121983
False Positive:  67
False Negative:  91
Confusion Matrix: 
[[868  67]
 [ 91 507]]
Error rate for Decision Tree model (in %): 10.30658838878017
---------------------

# Support Vector Machines (SVM)

In [69]:
kfold=KFold(n_splits=2, shuffle=True)
for train_index, test_index in kfold.split(spam_data):
    print("TRAIN:", train_index, "TEST:", test_index)
    training_features,testing_features=spam_data[train_index], spam_data[test_index]
    training_labels,testing_labels=spam_label[train_index], spam_label[test_index]
    #training the training features with the training labels by fitting it into the Linear SVM
    svclassifier = SVC(kernel='linear')  
    svclassifier.fit(training_features,training_labels)
    labels_svm = svclassifier.predict(testing_features) 
    #Metric for Linear SVM: Accuracy
    print("SVM model accuracy(in %):", metrics.accuracy_score(testing_labels, labels_svm)*100)
    #confusion Matrix: SVM
    conf_matrix=confusion_matrix(testing_labels, labels_svm)
    print("False Positive: ",conf_matrix[0][1])
    print("False Negative: ",conf_matrix[1][0])
    print("Confusion Matrix: ")
    print(confusion_matrix(testing_labels, labels_svm)) 
    error_rate=100-metrics.accuracy_score(testing_labels, labels_svm)*100
    print("Error rate for Decision Tree model (in %):", error_rate)
    print("----------------------------------------------------------------")

TRAIN: [   2    3    4 ... 4596 4597 4598] TEST: [   0    1    7 ... 4595 4599 4600]
SVM model accuracy(in %): 93.26379834854411
False Positive:  71
False Negative:  84
Confusion Matrix: 
[[1337   71]
 [  84  809]]
Error rate for Decision Tree model (in %): 6.736201651455886
----------------------------------------------------------------
TRAIN: [   0    1    7 ... 4595 4599 4600] TEST: [   2    3    4 ... 4596 4597 4598]
SVM model accuracy(in %): 92.56521739130434
False Positive:  68
False Negative:  103
Confusion Matrix: 
[[1312   68]
 [ 103  817]]
Error rate for Decision Tree model (in %): 7.434782608695656
----------------------------------------------------------------
